### ISSUE TITLE
Issue with create_iso.sh: "cp: cannot stat 'kernel.elf': No such file or directory"

### ISSUE THREAD

**Issue by moussacodes** [lvntky/ArtilleryOS#46]
### Description:
I encountered an issue while running the scripts/create_iso.sh. The error message:

[INFO] copying kernel.elf to iso/boot/...
cp: cannot stat 'kernel.elf': No such file or directory

also [Installation Guide](https://github.com/lvntky/ArtilleryOS/blob/master/docs/installation-guide.md) is giving 404 - page not found

**Comment by lvntky** [comment]
Hi @moussacodes thank you for great information. 

The issue you faced is caused because you haven't create the elf file yet by compiling the source code of Artilerry OS. All you have to do is:
1: `make clean`
2. `make iso`

when you run these commands, the `make iso` command will create a bootable ISO image for you by using scripts/create_iso.sh. 

And thank you for the feedback, we will create the Installation guide for new comers. Thank you for your interest! I hope this solution will work for you, if you face up a issue still you can always write up here.
